Repository Antititi-time/T.TIME_CLIENT, pull requests merged in 2023-02, with the labels that each got.

#106 [chat, myResult] 3차 QA chat, myResult 수정
  src/assets/icons/index.ts
  src/assets/icons/smallLogoIcon.svg
  src/assets/images/img_chat_logo.png
  src/assets/images/index.ts
  src/components/chat/InputAnswer.tsx
  src/components/chat/TopBar.tsx
  src/pages/myResult/[teamId]/[userId].tsx
Labels: 🎨 style

#109 [myResult, teamResult] 공유하기 관련 3차 QA 수정 사항
  public/img_personalShare.png
  public/img_teamShare.png
  src/components/shareModule/MyResultModal.tsx
  src/components/shareModule/TeamModal.tsx
Labels: 🐛 fix

#108 [myResult] LocalStorage 조건부 로직 추가
  src/components/myResult/ResultGraph.tsx
  src/components/teamResult/UnfinishedResult.tsx
Labels: 🐛 fix

#111 [common] 카카오 링크 복사 썸네일 및 문구 변경
  src/components/common/LogoTop.tsx
  src/components/common/SEO.tsx
  src/pages/myResult/[teamId]/[userId].tsx
  src/pages/teamResult/[teamId]/[userId].tsx
Labels: ✨ feat

#113 [common] 로그인 작업 전 수정 사항 최종 반영
  src/components/teamResult/ResultFrame.tsx
  src/components/teamResult/SimpleResult.tsx
  src/pages/invite/[teamId].tsx
  src/pages/myResult/[teamId]/[userId].tsx
  src/pages/teamResult/[teamId]/[userId].tsx
Labels: 🧹 chore, ✨ feat

#121 [teamResult] chart.js 버전 업그레이드 및 차트 배경 코드 수정
  package.json
  src/components/teamResult/Chart.tsx
  yarn.lock
Labels: 🐛 fix

#122 [common] 구글 소셜 로그인 (서버 작업 전)
  package.json
  src/assets/icons/icn_google.svg
  src/assets/icons/index.ts
  src/atoms/login.ts
  src/components/common/GoogleLoginButton.tsx
  src/pages/index.tsx
  yarn.lock
Labels: ✨ feat

#124 [chat] 프로그레스바 구현
  src/components/chat/ChatBody.tsx
  src/components/chat/ChoiceAnswer.tsx
  src/components/chat/FirstChoiceAnswer.tsx
  src/components/chat/InputAnswer.tsx
  src/components/chat/TopBar.tsx
  src/pages/chat/[teamId]/[userId].tsx
Labels: ✨ feat
