Repository Antititi-time/T.TIME_CLIENT, pull requests merged in 2023-01, with the labels that each got.

#6 [common] 색상 및 폰트 정리
  src/assets/images/img_top_logo.svg
  src/assets/images/index.ts
  src/components/common/ImageDiv.tsx
  src/pages/example.tsx
  src/styles/color.ts
  src/styles/fontStyle.ts
Labels: 🗂 asset

#10 [HomePage] UI, 버튼 기능(캐릭터 이미지 빼고)
  src/assets/icon/index.ts
  src/assets/icon/logoIcon.svg
  src/pages/example.tsx
  src/pages/index.tsx
  src/styles/color.ts
  src/styles/fontStyle.ts
Labels: 💅 design, ✨ feat

#14 [teamResult] 팀 결과 페이지 퍼블리싱
  src/assets/icons/index.ts
  src/assets/images/img_century_gothic_logo.png
  src/assets/images/img_top_logo.png
  src/assets/images/img_top_logo.svg
  src/assets/images/index.ts
  src/components/common/BottomButton.tsx
  src/components/common/BottomButtonContainer.tsx
  src/components/common/LogoTop.tsx
  src/components/teamResult/Chart.tsx
  src/components/teamResult/DetailResult.tsx
  src/components/teamResult/ResultFrame.tsx
  src/components/teamResult/SimpleResult.tsx
  src/pages/_document.tsx
  src/pages/teamResult/[teamCode].tsx
  src/styles/color.ts
  src/styles/fontStyle.ts
Labels: 💅 design, ✨ feat

#20 [asset] 넥슨 볼드체 추가
  src/styles/fontStyle.ts
Labels: 🗂 asset

#25 [join] 참여하기 UI 구현
  src/assets/icons/ic_join_round.svg
  src/assets/icons/index.ts
  src/assets/images/img_century_gothic_logo.png
  src/components/join/JoinTop.tsx
  src/pages/join.tsx
  src/styles/globalStyle.ts
Labels: 💅 design, ✨ feat

#27 [invite] 팀 입력 기능
  src/components/invite/TeamInput.tsx
  src/pages/invite.tsx
Labels: 🧹 chore, 💅 design

#33 [common] api 세팅
  .env.development
  src/components/teamResult/SimpleResult.tsx
  src/services/base.ts
  src/services/index.ts
Labels: ✨ feat

#32 [common] joinTop 공통 컴포넌트화 및 스크롤링 방지 훅스 구현
  src/components/common/TextTop.tsx
  src/hooks/UseManageScroll.ts
  src/pages/invite.tsx
  src/pages/join.tsx
Labels: 🧹 chore, 🔨 refactor

#34 [myResult]개인결과 페이지 스타일링 및 기능 구현
  .env
  next.config.js
  src/assets/icons/icn_dots.svg
  src/assets/icons/index.ts
  src/components/myResult/ResultGraph.tsx
  src/components/shareModule/InviteModal.tsx
  src/components/shareModule/TeamModal.tsx
  src/constants/myResult/resultMessage.ts
  src/hooks/FilterQuestionType.ts
  src/hooks/SetConstantIndex.ts
  src/mocks/handlers.ts
  src/mocks/types.ts
  src/pages/myResult/[teamcode]/[userId].tsx
  src/services/index.ts
  src/styles/color.ts
Labels: 💅 design, ✨ feat

#43 [chat] 질문자 질문 채팅 뷰 만들기
  src/assets/icons/A_icon1.svg
  src/assets/icons/A_icon2.svg
  src/assets/icons/B_icon1.svg
  src/assets/icons/B_icon2.svg
  src/assets/icons/C_icon1.svg
  src/assets/icons/C_icon2.svg
  src/assets/icons/D_icon1.svg
  src/assets/icons/D_icon2.svg
  src/assets/icons/D_icon3.svg
  src/assets/icons/E_icon1.svg
  src/assets/icons/E_icon2.svg
  src/assets/icons/End_icon.svg
  src/assets/icons/index.ts
  src/assets/icons/profileImg.svg
  src/assets/icons/testEmoticon.svg
  src/components/chat/AdminProfile.tsx
  src/components/chat/ChatBody.tsx
  src/components/chat/ChatStartTalk.tsx
  src/components/chat/TopBar.tsx
  src/constants/chat/chatQuestion.ts
  src/pages/chat/[teamCode]/[userId].tsx
Labels: 💅 design, ✨ feat

#40 [myResult] 개인결과 뷰 이미지 렌더링 및 텍스트 수정, 조건부 행간 추가
  src/assets/icons/index.ts
  src/assets/images/img_canele.png
  src/assets/images/img_eclair.png
  src/assets/images/img_makarong.png
  src/assets/images/img_saltbread.png
  src/assets/images/img_tart.png
  src/assets/images/index.ts
  src/components/myResult/ResultGraph.tsx
  src/constants/myResult/resultMessage.ts
  src/pages/myResult/[teamcode]/[userId].tsx
Labels: 🗂 asset, 🧹 chore, 💅 design

#44 [teamResult] 티타임 미완료 페이지 구현
  .env
  src/assets/icons/index.ts
  src/components/teamResult/SimpleResult.tsx
  src/components/teamResult/UnfinishedResult.tsx
  src/pages/myResult/[teamcode]/[userId].tsx
  src/pages/teamResult/[teamCode]/[userId].tsx
  src/services/index.ts
Labels: 💅 design, ✨ feat

#46 [teamResult] 팀 결과 실서버 연결
  src/assets/images/img_canele_negative.png
  src/assets/images/img_canele_positive.png
  src/assets/images/img_eclair_negative.png
  src/assets/images/img_eclair_positive.png
  src/assets/images/img_macaron_negative.png
  src/assets/images/img_macaron_positive.png
  src/assets/images/img_saltbread_negative.png
  src/assets/images/img_saltbread_positive.png
  src/assets/images/img_tart_negative.png
  src/assets/images/img_tart_positive.png
  src/assets/images/index.ts
  src/components/common/BottomButtonContainer.tsx
  src/components/teamResult/Chart.tsx
  src/components/teamResult/DetailResult.tsx
  src/components/teamResult/ResultFrame.tsx
  src/components/teamResult/SimpleResult.tsx
  src/constants/teamResult/questionText.ts
  src/hooks/FilterQuestionType.ts
  src/pages/teamResult/[teamCode]/[userId].tsx
  src/services/index.ts
  src/services/types.ts
Labels: 💅 design, ✨ feat

#48 [teamResult] 팀결과 -> 공유하기 연결, 조건부 하단 버튼 ,유저 판별기능 구현
  src/assets/images/img_error_chr.png
  src/assets/images/index.ts
  src/components/common/BottomButton.tsx
  src/components/common/BottomButtonContainer.tsx
  src/components/myResult/ResultGraph.tsx
  src/components/shareModule/TeamModal.tsx
  src/components/teamResult/BottomButtonContainer.tsx
  src/components/teamResult/DetailResult.tsx
  src/components/teamResult/SimpleResult.tsx
  src/components/teamResult/UnfinishedResult.tsx
  src/pages/team/result.tsx
  src/pages/teamResult/[teamCode]/[userId].tsx
Labels: ✨ feat

#57 [invite] 초대장 만들기 페이지 확인 기능 구현
  src/assets/images/img_invite.png
  src/assets/images/img_letter.png
  src/assets/images/index.ts
  src/components/common/BottomButton.tsx
  src/components/invite/TeamInput.tsx
  src/pages/invite.tsx
  src/pages/invite/[teamCode].tsx
  src/services/index.ts
  src/services/types.ts
Labels: 🧹 chore, ✨ feat, 🐛 fix

#62 [chat] 채팅 로직 구현
  src/assets/icons/index.ts
  src/components/chat/ChatBody.tsx
  src/components/chat/ChatStartTalk.tsx
  src/components/chat/ChoiceAnswer.tsx
  src/components/chat/FirstChoiceAnswer.tsx
  src/components/chat/InputAnswer.tsx
  src/components/chat/TopBar.tsx
  src/components/chat/WatchMyResultButton.tsx
  src/components/teamResult/SimpleResult.tsx
  src/constants/chat/chatQuestion.ts
  src/pages/chat/[teamCode]/[userId].tsx
  src/services/index.ts
Labels: 💅 design, ✨ feat

#59 [join] join페이지 마무리 작업
  src/assets/images/img_join.png
  src/assets/images/index.ts
  src/pages/join/[teamCode].tsx
Labels: 🗂 asset, ✨ feat

#61 [common] 차트 backgroundColor 타입 지정 오류 해결 & 카테고리 이모티콘 지정
  package.json
  src/assets/icons/icn_teamResult_a.svg
  src/assets/icons/icn_teamResult_b.svg
  src/assets/icons/icn_teamResult_c.svg
  src/assets/icons/icn_teamResult_d.svg
  src/assets/icons/icn_teamResult_e.svg
  src/assets/icons/index.ts
  src/components/teamResult/Chart.tsx
  src/components/teamResult/DetailResult.tsx
  yarn.lock
Labels: 💅 design, 🐛 fix

#64 [myResult] 이미지 저장 기능 구현
  package-lock.json
  package.json
  src/components/myResult/BottomBtnContainer.tsx
  src/components/myResult/ImgDownload.ts
  src/constants/myResult/resultMessage.ts
  src/pages/_document.tsx
  src/pages/myResult/[teamcode]/[userId].tsx
  yarn.lock
Labels: 💅 design, ✨ feat

#65 [invite] 초대장 공유하기 뷰 연결 및 Api 통신 구현
  src/components/shareModule/InviteModal.tsx
  src/pages/invite/[teamCode].tsx
Labels: 🧹 chore, ✨ feat

#66 [chat] 전체 스타일링, 스크롤 하단 고정
  src/assets/icons/A_icon1.svg
  src/assets/icons/A_icon2.svg
  src/assets/icons/B_icon1.svg
  src/assets/icons/B_icon2.svg
  src/assets/icons/C_icon1.svg
  src/assets/icons/C_icon2.svg
  src/assets/icons/D_icon1.svg
  src/assets/icons/D_icon2.svg
  src/assets/icons/D_icon3.svg
  src/assets/icons/E_icon1.svg
  src/assets/icons/E_icon2.svg
  src/assets/icons/End_icon.svg
  src/assets/icons/index.ts
  src/assets/icons/profileImg.svg
  src/assets/icons/testEmoticon.svg
  src/assets/images/A_icon1.png
  src/assets/images/A_icon2.png
  src/assets/images/B_icon1.png
  src/assets/images/B_icon2.png
  src/assets/images/C_icon1.png
  src/assets/images/C_icon2.png
  src/assets/images/D_icon1.png
  src/assets/images/D_icon2.png
  src/assets/images/D_icon3.png
  src/assets/images/E_icon1.png
  src/assets/images/E_icon2.png
  src/assets/images/End_icon.png
  src/assets/images/index.ts
  src/assets/images/profileImg.png
  src/components/chat/AdminProfile.tsx
  src/components/chat/ChatBody.tsx
  src/components/chat/ChatStartTalk.tsx
  src/components/chat/ChoiceAnswer.tsx
  src/components/chat/FirstChoiceAnswer.tsx
  src/components/chat/InputAnswer.tsx
  src/constants/chat/chatQuestion.ts
  src/constants/teamResult/questionText.ts
  src/pages/invite/index.tsx
Labels: 🧹 chore, 💅 design, ✨ feat

#71 [feat] 팀정보 가져오기 api 연결
  src/pages/join/[teamCode].tsx
  src/services/index.ts
Labels: ✨ feat

#72 [common] SEO 설정
  .gitignore
  public/favicon.ico
  src/assets/images/img_thumbnail.png
  src/components/common/SEO.tsx
  src/pages/_document.tsx
  src/pages/index.tsx
Labels: ✨ feat

#75 [common] SEO 설정 수정 및 코드 정리
  .env.development
  .gitignore
  public/img_thumbnail.png
  public/next.svg
  public/thirteen.svg
  public/vercel.svg
  src/components/common/SEO.tsx
  src/components/teamResult/Chart.tsx
  src/components/teamResult/SimpleResult.tsx
  src/hooks/FilterQuestionType.ts
  src/pages/404.tsx
  src/pages/_document.tsx
  src/pages/chat/[teamCode]/[userId].tsx
  src/pages/index.tsx
  src/pages/invite/[teamCode].tsx
  src/pages/invite/index.tsx
  src/pages/join/[teamCode].tsx
  src/pages/myResult/[teamcode]/[userId].tsx
  src/pages/teamResult/[teamCode]/[userId].tsx
Labels: 🐛 fix, 🎨 style

#76 [design] 메인 페이지 배경 스타일링 및 애니메이션
  src/assets/images/img_background_items.png
  src/assets/images/img_main_background.png
  src/assets/images/img_main_characters.png
  src/assets/images/index.ts
  src/components/chat/ChatBody.tsx
  src/components/chat/InputAnswer.tsx
  src/pages/index.tsx
Labels: 🧹 chore, 💅 design

#78 [chore] 채팅 페이지 디자인 수정
  src/components/chat/ChatBody.tsx
  src/components/chat/TopBar.tsx
Labels: 💅 design

#82 [fix] CSR->SSR 데이터 처리 방식 변경
  src/components/teamResult/ResultFrame.tsx
  src/components/teamResult/SimpleResult.tsx
  src/pages/teamResult/[teamCode]/[userId].tsx
Labels: 🐛 fix

#85 [teamResult] 카테고리 아이콘 png로 변경/ 상세 결과 이름순 정렬
  src/assets/icons/icn_teamResult_a.svg
  src/assets/icons/icn_teamResult_b.svg
  src/assets/icons/icn_teamResult_c.svg
  src/assets/icons/icn_teamResult_d.svg
  src/assets/icons/icn_teamResult_e.svg
  src/assets/icons/index.ts
  src/assets/images/img_category_a.png
  src/assets/images/img_category_b.png
  src/assets/images/img_category_c.png
  src/assets/images/img_category_d.png
  src/assets/images/img_category_e.png
  src/assets/images/index.ts
  src/components/teamResult/DetailResult.tsx
Labels: 🐛 fix

#87 [chore] QA 이슈 사항 수정
  src/assets/icons/index.ts
  src/assets/images/B_icon1.png
  src/assets/images/B_icon2.png
  src/assets/images/C_icon2.png
  src/assets/images/img_kakao.png
  src/assets/images/index.ts
  src/components/chat/ChatBody.tsx
  src/components/chat/InputAnswer.tsx
  src/components/shareModule/InviteModal.tsx
  src/components/shareModule/TeamModal.tsx
  src/constants/chat/chatQuestion.ts
Labels: 🗂 asset, 🧹 chore, 💅 design

#90 [teamResult] 코드 정리
  src/components/common/SEO.tsx
  src/components/shareModule/InviteModal.tsx
  src/components/shareModule/TeamModal.tsx
  src/components/teamResult/BottomButtonContainer.tsx
  src/components/teamResult/Chart.tsx
  src/components/teamResult/DetailResult.tsx
  src/components/teamResult/ResultFrame.tsx
  src/components/teamResult/SimpleResult.tsx
  src/components/teamResult/UnfinishedResult.tsx
  src/constants/teamResult/categoryList.ts
  src/pages/teamResult/[teamCode]/[userId].tsx
  src/pages/teamResult/[teamId]/[userId].tsx
Labels: 🎨 style

#97 [teamResult] SSR props -> isReady 로직 구현
  src/pages/myResult/[teamId]/[userId].tsx
  src/pages/teamResult/[teamId]/[userId].tsx
Labels: 🧹 chore

#96 [myResult] 코드 정리 및 SSR props -> isReady 로직 구현
  src/components/shareModule/InviteModal.tsx
  src/components/shareModule/TeamModal.tsx
  src/mocks/handlers.ts
  src/mocks/types.ts
  src/pages/invite/[teamCode].tsx
  src/pages/myResult/[teamId]/[userId].tsx
  src/services/types.ts
Labels: 🧹 chore

#92 [chat] 코드 정리
  src/components/chat/ChatBody.tsx
  src/components/chat/InputAnswer.tsx
  src/pages/chat/[teamId]/[userId].tsx
Labels: 🎨 style

#98 [join] 코드 정리
  src/pages/join/[teamId].tsx
Labels: 🧹 chore, 🎨 style

#101 [invite] 코드 정리
  src/pages/invite/[teamCode].tsx
  src/pages/invite/index.tsx
Labels: 🧹 chore

#99 [myResult] 공유 모달 구현
  src/components/myResult/BottomBtnContainer.tsx
  src/components/myResult/ImgDownload.ts
  src/components/shareModule/MyResultModal.tsx
  src/components/shareModule/ShareKakao.tsx
  src/pages/myResult/[teamId]/[userId].tsx
Labels: ✨ feat

#103 [ShareModal] 공유하기 페이지 이미지 변경 및 텍스트 변경
  src/assets/images/img_kakao_personalShare.jpg
  src/assets/images/img_kakao_teamShare.jpg
  src/components/shareModule/ShareKakao.tsx
Labels: 🗂 asset, 🧹 chore
