Repository Antititi-time/T.TIME_CLIENT, pull requests merged in 2023-03, with the labels that each got.

#128 [common] 구글 소셜 로그인 및 회원가입 실서버 연결
  src/components/common/GoogleLoginButton.tsx
  src/components/common/SEO.tsx
  src/components/shareModule/InviteModal.tsx
  src/components/shareModule/MyResultModal.tsx
  src/components/shareModule/TeamModal.tsx
  src/components/teamResult/DetailResult.tsx
  src/components/teamResult/UnfinishedResult.tsx
  src/constants/domain.ts
  src/pages/auth/google.tsx
  src/pages/index.tsx
  src/pages/invite/[teamId].tsx
  src/pages/myResult/[teamId]/[userId].tsx
  src/pages/teamResult/[teamId]/[userId].tsx
  src/services/index.ts
  src/services/types.ts
Labels: ✨ feat

#129 Feat/#116 카카오 소셜 로그인 및 회원가입 적용
  src/assets/icons/icn_kakaoLogin.svg
  src/assets/icons/index.ts
  src/components/chat/InputAnswer.tsx
  src/components/chat/WatchMyResultButton.tsx
  src/components/common/KakaoLoginButton.tsx
  src/pages/auth/kakao.tsx
  src/pages/invite/index.tsx
  src/pages/join/[teamId].tsx
  src/pages/myResult/[teamId]/[userId].tsx
  src/services/index.ts
  src/styles/color.ts
Labels: 💅 design, ✨ feat

#125 [ organizerOnboarding] 주최자 온보딩 페이지
  package.json
  src/assets/icons/icn_rectangle.svg
  src/assets/icons/index.ts
  src/assets/images/img_google_icon.png
  src/assets/images/img_kakao_icon.png
  src/assets/images/img_organizer_onboarding1.png
  src/assets/images/img_organizer_onboarding2.png
  src/assets/images/img_organizer_onboarding3.png
  src/assets/images/img_organizer_onboarding4.png
  src/assets/images/img_organizer_onboarding5.png
  src/assets/images/index.ts
  src/components/chat/ChatStartTalk.tsx
  src/components/common/GoogleLoginButton.tsx
  src/constants/organizerOnboarding/organizerSliderItems.ts
  src/pages/index.tsx
  src/pages/organizerOnboarding.tsx
  yarn.lock
Labels: 💅 design, ✨ feat

#126 [feat] 참여자 온보딩
  src/assets/images/img_canele_star.png
  src/assets/images/img_participant_canele.png
  src/assets/images/img_participant_first.png
  src/assets/images/img_participant_fourth.png
  src/assets/images/img_participant_second.png
  src/assets/images/img_participant_tart.png
  src/assets/images/img_participant_third.png
  src/assets/images/img_tart_star.png
  src/assets/images/index.ts
  src/pages/participantOnboarding.tsx
  src/styles/fontStyle.ts
Labels: 💅 design, ✨ feat

#127 [myPage] 마이페이지 구현
  src/pages/index.tsx
  src/pages/myPage/index.tsx
  src/services/base.ts
  src/services/index.ts
Labels: 💅 design, ✨ feat, 🐛 fix

#134 [organizerOnboarding] 로그인 버튼 디자인 수정
  src/components/common/GoogleLoginButton.tsx
  src/pages/organizerOnboarding.tsx
Labels: 💅 design

#135 [participantOnboarding / Main]QA반영
  src/pages/auth/google.tsx
  src/pages/auth/kakao.tsx
  src/pages/index.tsx
  src/pages/myPage/index.tsx
  src/pages/participantOnboarding.tsx
Labels: ✨ feat

#136 [join] 로그인 여부에 따른 참가자 온보딩 페이지 로직 구현
  src/pages/join/[teamId].tsx
  src/pages/participantOnboarding.tsx
  src/services/index.ts
Labels: 🧹 chore, ✨ feat

#138 [Onboarding]QA반영 참여자, 주최자 온보딩 수정
  src/pages/organizerOnboarding.tsx
  src/pages/participantOnboarding.tsx
  src/styles/fontStyle.ts
Labels: 🧹 chore, 💅 design

#141 [fix] join페이지 SEO 코드 추가
  src/pages/join/[teamId].tsx
Labels: 🐛 fix

#147 [QA] QA 수정 사항 반영
  src/assets/images/img_logo_main_icon.png
  src/components/chat/ChatBody.tsx
  src/pages/index.tsx
  src/pages/organizerOnboarding.tsx
  src/pages/participantOnboarding.tsx
Labels: 🧹 chore

#150 [onboarding, myResult] 자잘한 2차 QA 해결
  src/components/shareModule/MyResultModal.tsx
  src/components/shareModule/TeamModal.tsx
  src/constants/myResult/resultMessage.ts
  src/pages/join/[teamId].tsx
  src/pages/organizerOnboarding.tsx
Labels: 🧹 chore, 🐛 fix

#152 [myPage] 마이페이지 예외 처리 및 UI 구현
  public/assets/images/img_no_history.png
  public/assets/images/index.ts
  src/components/common/Error.tsx
  src/components/myPage/NonePage.tsx
  src/pages/404.tsx
  src/pages/myPage/index.tsx
  src/pages/myResult/[teamId]/[userId].tsx
  src/pages/unfinished.tsx
Labels: 💅 design, ✨ feat

#154 [feat] GA,GTM 적용
  package.json
  src/lib/gtag.ts
  src/pages/_app.tsx
  tsconfig.json
  yarn.lock
Labels: ✨ feat

#157 [common] join 페이지 auth check, onboarding 건너뛰기 로직 변경
  src/components/shareModule/InviteModal.tsx
  src/components/shareModule/MyResultModal.tsx
  src/components/shareModule/TeamModal.tsx
  src/pages/invite/[teamId].tsx
  src/pages/join/[teamId].tsx
  src/pages/organizerOnboarding.tsx
  src/services/auth.tsx
Labels: 🐛 fix

#159 [common] userId base64 형식으로 변경
  src/components/chat/ChatBody.tsx
  src/components/chat/InputAnswer.tsx
  src/mocks/types.ts
  src/pages/myResult/[teamId]/[userId].tsx
  src/services/index.ts
  src/services/types.ts
Labels: 🔨 refactor
