Repository Antititi-time/T.TIME_CLIENT, pull requests merged in 2023-06, with the labels that each got.

#179 [join] 참여하기 페이지 반응형 구현
  public/assets/images/img_join.png
  src/pages/join/[teamId].tsx
  src/styles/fontStyle.ts
Labels: 💅 design

#180 [chat] 채팅 페이지 / TextTop 반응형 구현
  src/components/chat/ChatBody.tsx
  src/components/chat/ChoiceAnswer.tsx
  src/components/chat/FirstChoiceAnswer.tsx
  src/components/chat/InputAnswer.tsx
  src/components/chat/WatchMyResultButton.tsx
  src/components/common/TextTop.tsx
Labels: 💅 design

#177 [feat]주최자 페이지 반응형
  src/components/common/ToolTip.tsx
  src/pages/organizerOnboarding.tsx
Labels: ✨ feat

#183 [common] 팀결과 페이지/404/로딩중/메인/마이페이지 반응형 구현
  src/components/common/Error.tsx
  src/components/common/LoadingView.tsx
  src/components/common/LogoTop.tsx
  src/components/myPage/NonePage.tsx
  src/components/teamResult/BottomButtonContainer.tsx
  src/components/teamResult/Chart.tsx
  src/components/teamResult/DetailResult.tsx
  src/components/teamResult/ResultFrame.tsx
  src/components/teamResult/SimpleResult.tsx
  src/pages/index.tsx
  src/pages/myPage/index.tsx
  src/pages/organizerOnboarding.tsx
  src/pages/teamResult/[teamId]/[userId].tsx
  src/pages/unfinished.tsx
  src/styles/fontStyle.ts
Labels: 💅 design

#174 [shareModal] 공유 모달 반응형 구현
  src/components/shareModule/InviteModal.tsx
  src/components/shareModule/MyResultModal.tsx
  src/components/shareModule/ShareKakao.tsx
  src/components/shareModule/TeamModal.tsx
Labels: 🧹 chore, 💅 design, ✨ feat

#181 [myResult] 개인결과 반응형 페이지 구현
  src/components/myResult/ResultGraph.tsx
  src/pages/myResult/[teamId]/[userId].tsx
  src/styles/fontStyle.ts
Labels: 💅 design, ✨ feat

#185 [teamResult] 팀원 미완료 페이지 반응형 구현
  src/components/myResult/ResultGraph.tsx
  src/components/teamResult/UnfinishedResult.tsx
  src/pages/myResult/[teamId]/[userId].tsx
Labels: 🧹 chore, 💅 design, ✨ feat

#188 [organizerOnboarding] 반응형 수정
  src/components/common/ToolTip.tsx
  src/pages/organizerOnboarding.tsx
Labels: 🎨 style

#203 [Invite] 반응형 수정
  src/components/invite/TeamInput.tsx
  src/pages/invite/[teamId].tsx
  src/pages/invite/index.tsx
  src/styles/fontStyle.ts
Labels: 💅 design, ✨ feat

#204 [participantOnBoarding] 반응형 수정
  src/pages/participantOnboarding.tsx
Labels: 💅 design, ✨ feat

#200 [common] 팀결과 페이지/404/로딩중/메인/마이페이지 반응형 수정
  public/assets/images/img_main_characters_big.png
  public/assets/images/index.ts
  src/components/common/Error.tsx
  src/components/common/LoadingView.tsx
  src/components/teamResult/Chart.tsx
  src/components/teamResult/DetailResult.tsx
  src/components/teamResult/ResultFrame.tsx
  src/components/teamResult/SimpleResult.tsx
  src/pages/index.tsx
  src/pages/myPage/index.tsx
  src/pages/myResult/[teamId]/[userId].tsx
  src/pages/teamResult/[teamId]/[userId].tsx
  src/styles/fontStyle.ts
Labels: 💅 design

#199 [myResult] 개인 결과 페이지 반응형 수정
  src/components/myResult/ResultGraph.tsx
  src/components/teamResult/UnfinishedResult.tsx
  src/pages/myResult/[teamId]/[userId].tsx
Labels: 🧹 chore, 💅 design, ✨ feat

#202 [chat] 채팅 반응형 수정
  src/components/chat/ChatBody.tsx
  src/components/chat/ChoiceAnswer.tsx
  src/components/chat/FirstChoiceAnswer.tsx
  src/components/chat/InputAnswer.tsx
  src/components/chat/WatchMyResultButton.tsx
Labels: 💅 design

#201 [join] 참여하기 반응형 수정
  src/pages/join/[teamId].tsx
Labels: 💅 design
